services:
  landingpage:
    build: .
    container_name: moodbites-landingpage
    ports:
      - "80:80"
    volumes:
      - /home/moodbites/apk/moodbites.apk:/usr/share/nginx/html/moodbites.apk:ro
    restart: unless-stopped
